#!/usr/bin/env bash
# gameday step 4 — boot the rebuilt DLLs on a THROWAWAY 4th server and triage the load.
#
#   smoke.sh <label> [--steamcmd-args "<args>"] [--world-from <dir>] [--keep] [--no-teardown]
#
# Creates /opt/valheim-gameday (compose copied from /opt/valheim-test, ports 2486-2488,
# container `valheim-gameday`, restart: no, its own world, BEPINEX=true), copies the freshly
# built plugin DLLs in, boots, greps the log, prints a module -> status -> error triage table,
# then `docker compose down`. Never touches /opt/valheim, /opt/valheim2 or /opt/valheim-test.
#
# NOTE: the first run downloads the game (~1-2 GB) into /opt/valheim-gameday/data. Keep the
# folder (default) so later runs on the same branch start in ~1 min instead of ~10.
set -euo pipefail
cd "$(dirname "$0")"; . ./_common.sh

LABEL="${1:-}"; shift || true
[ -n "$LABEL" ] || die "usage: smoke.sh <label> [--steamcmd-args \"...\"] [--world-from <dir>] [--keep]"

GD="${GAMEDAY_DIR:-/opt/valheim-gameday}"
STEAM_ARGS="${STEAMCMD_ARGS_DEFAULT:--beta public-test -betapassword yesimadebackups}"
WORLD_FROM=""; TEARDOWN=1; BOOT_TIMEOUT="${BOOT_TIMEOUT:-900}"
while [ $# -gt 0 ]; do
  case "$1" in
    --steamcmd-args) STEAM_ARGS="$2"; shift 2;;
    --world-from)    WORLD_FROM="$2"; shift 2;;
    --keep|--no-teardown) TEARDOWN=0; shift;;
    *) die "unknown arg: $1";;
  esac
done
case "$GD" in /opt/valheim|/opt/valheim2|/opt/valheim-test) die "GAMEDAY_DIR must not be a real server dir";; esac
guard_write "$GD"

timer_start
say "smoke: booting '$LABEL' on the throwaway gameday server ($GD, ports 2486-2488)"
mkdir -p "$GD/config/bepinex/plugins" "$GD/config/worlds_local" "$GD/data"

# ---------- compose (derived from valheim-test, ports + name + branch changed) ----------
cat > "$GD/docker-compose.yaml" <<COMPOSE
# THROWAWAY game-day smoke server. Generated by tools/gameday/smoke.sh — safe to delete.
# NOT a real server: private, no backups, no auto-update, restart: no.
services:
  valheim:
    image: ghcr.io/community-valheim-tools/valheim-server:latest
    container_name: valheim-gameday
    stop_grace_period: 30s
    restart: "no"
    ports:
      - "2486-2488:2486-2488/udp"
    volumes:
      - ./config:/config
      - ./data:/opt/valheim
    environment:
      - SERVER_NAME=GAMEDAY
      - WORLD_NAME=GAMEDAY
      - SERVER_PASS=gameday
      - SERVER_PUBLIC=false
      - SERVER_PORT=2486
      - STEAMCMD_ARGS=$STEAM_ARGS
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WORLDS_FILE_PERMISSIONS=755
      - PRE_SERVER_RUN_HOOK=find /config/worlds_local -type d ! -perm -0100 -exec chmod 0755 {} + 2>/dev/null || true
      - BACKUPS=false
      - UPDATE_CRON=
      - RESTART_CRON=
      - CROSSPLAY=false
      - BEPINEX=true
COMPOSE

[ -n "$WORLD_FROM" ] && { info "copying world from $WORLD_FROM"; rsync -a "$WORLD_FROM/" "$GD/config/worlds_local/"; }

# ---------- plugins ----------
rm -rf "$GD/config/bepinex/plugins"/{NoVikingLeftBehind,SmoothServer}
COPIED=()
for P in NoVikingLeftBehind SmoothServer; do
  B="$LAB/src/$P/bin"
  if [ -f "$B/$P.dll" ]; then
    mkdir -p "$GD/config/bepinex/plugins/$P"
    # main DLL + any runtime deps sitting next to it (ZstdSharp + BCL shims for SmoothServer)
    cp "$B"/*.dll "$GD/config/bepinex/plugins/$P/"
    COPIED+=("$P ($(ls "$GD/config/bepinex/plugins/$P" | wc -l) dll)")
  else
    info "SKIP $P — no build output at $B/$P.dll (compile failed?)"
  fi
done
# Extra plugin folders to include as-is, e.g. the LAST-GOOD build of a mod whose rebuild failed.
# This is the realistic day-one mix: some mods rebuilt, some still shipping yesterday's DLL.
for X in ${EXTRA_PLUGIN_DIRS:-}; do
  [ -d "$X" ] || { info "EXTRA_PLUGIN_DIRS: no such dir $X"; continue; }
  N=$(basename "$X"); mkdir -p "$GD/config/bepinex/plugins/$N"
  cp "$X"/*.dll "$GD/config/bepinex/plugins/$N/"
  COPIED+=("$N (pre-built, from $X)")
done
[ ${#COPIED[@]} -gt 0 ] || die "nothing to smoke-test — both builds failed"
info "plugins: ${COPIED[*]}"

# also drop stale copies the image keeps inside the game volume
rm -rf "$GD/data/bepinex/BepInEx/plugins"/{NoVikingLeftBehind,SmoothServer} 2>/dev/null || true

# ---------- boot ----------
T0=$(date -u +%FT%TZ)
( cd "$GD" && docker compose up -d ) >/dev/null
BOOTED=0
for i in $(seq 1 $((BOOT_TIMEOUT/5))); do
  sleep 5
  L=$(docker logs --since "$T0" valheim-gameday 2>&1 || true)
  if grep -q "Game server connected" <<<"$L"; then BOOTED=1; break; fi
  if grep -qE "Chainloader startup complete" <<<"$L" && [ $i -gt 20 ]; then break; fi
done
sleep 20
LOGF="$(label_dir "$LABEL")/smoke.log"; guard_write "$LOGF"
docker logs --since "$T0" valheim-gameday > "$LOGF" 2>&1 || true
info "boot reached 'Game server connected': $([ $BOOTED = 1 ] && echo yes || echo NO)  (full log: $LOGF)"

# ---------- triage ----------
say "version / loader"
grep -aoE "Valheim l?-?[0-9.]+ \(network version [0-9]+\)|BepInEx [0-9.]+ - valheim|Chainloader started|Chainloader startup complete|[0-9]+ plugins to load" "$LOGF" | sort -u | sed 's/^/   /'

say "our plugins"
grep -aE "NoVikingLeftBehind|SmoothServer" "$LOGF" | grep -aE "Loading|module summary|FAILED|OK|version" | sed 's/^/   /' | head -40

set +e   # every grep below may legitimately find nothing; head closing a pipe trips pipefail

say "TRIAGE TABLE — mod -> module -> status"
TRIAGE="$(label_dir "$LABEL")/TRIAGE.md"
{
  printf '| mod | module | status |\n|---|---|---|\n'
  # The "<Mod> module summary: A=applied, B=FAILED(...)" line is the authoritative verdict.
  grep -a "module summary:" "$LOGF" | tr -d '\r' | while IFS= read -r line; do
    MOD=$(sed -E 's/.*[]:[ ]([A-Za-z]+) module summary:.*/\1/' <<<"$line")
    sed -E 's/^.*module summary: //; s/, ([A-Za-z0-9_]+=)/\n\1/g' <<<"$line" \
      | sed -E "s#^([A-Za-z0-9_]+)=(.*)\$#| $MOD | \1 | \2 |#"
  done
} | tee "$TRIAGE" | sed 's/^/   /'
grep -q '^|.*|.*|' "$TRIAGE" || info "   NO MODULE SUMMARY — the plugin never reached ZNet.Start (hard load failure; see below)"

say "FAILED / exception detail"
grep -aE "FAILED to patch|FAILED\(|MissingMethod|TypeLoad|MissingField|HarmonyException|Patching exception|Could not load|Unhandled exception|Chainloader.*error" "$LOGF" \
  | tr -d '\r' | grep -avE "ArgumentNullException: Value cannot be null|ThrowHelper|ShieldDomeImageEffect" \
  | sed -E 's/^.*supervisord: valheim-server //' | sort -u | sed 's/^/   /' | head -60
[ ${PIPESTATUS[0]:-1} -eq 0 ] || info "   none"

say "POST-BOOT runtime exception storm (patch said 'applied' but the method dies in Update)"
awk '/Game server connected/{seen=1} seen' "$LOGF" | tr -d '\r' \
  | grep -aoE "(MissingMethodException|MissingFieldException|TypeLoadException|NullReferenceException|InvalidCastException)[^ ].*" \
  | sed -E 's/^.*supervisord: valheim-server //' | sort | uniq -c | sort -rn | head -15 | sed 's/^/   /'
awk '/Game server connected/{seen=1} seen' "$LOGF" | grep -aoE "at \(wrapper dynamic-method\) [A-Za-z0-9_]+\.DMD<[^>]*>" \
  | sort -u | sed 's/^/   patched method involved: /' | head -15

say "transpiler assertions (silent-drift canaries)"
grep -aoE "transpiler.*(OK|expected).*" "$LOGF" | tr -d '\r' | sort -u | sed 's/^/   /' | head -20
set -e

# ---------- teardown ----------
if [ $TEARDOWN = 1 ]; then
  say "tearing down"
  ( cd "$GD" && docker compose down ) >/dev/null 2>&1 || true
  info "container down; $GD kept (game files cached for the next run). rm -rf $GD to reclaim the disk."
else
  info "left running (--keep). Stop with: cd $GD && docker compose down"
fi
timer_end "smoke $LABEL"
